import { Geist, Geist_Mono } from 'next/font/google';
import './css/globals.css';
import Navbar from '../components/Navbar/Navbar';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Stitches & Buttons',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
