import { Geist, Geist_Mono } from 'next/font/google';
import './css/globals.css';
import Navbar from '../components/Navbar/Navbar';
import Head from 'next/head';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Stitches & Buttons',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<Head>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0, viewport-fit=cover"
					key="viewportFitCover"
				></meta>
			</Head>

			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-hidden`}
				style={{ paddingTop: 'env(safe-area-inset-top)' }}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
